# Generated by Django 6.0.2 on 2026-02-20 01:51

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BuildingType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('extraction', 'Extracción'), ('construction', 'Construcción'), ('defense', 'Defensa'), ('other', 'Otro')], default='other', max_length=20)),
                ('description', models.TextField(blank=True)),
                ('cost', models.JSONField(default=dict, help_text="Costo base (ej: {'Plastilina': 100})")),
                ('production', models.JSONField(default=dict, help_text="Producción base (ej: {'Energía': 10})")),
            ],
        ),
        migrations.CreateModel(
            name='Galaxy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Vía Láctea', max_length=100)),
            ],
            options={
                'verbose_name_plural': 'Galaxies',
            },
        ),
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name='UnitType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('category', models.CharField(choices=[('ship', 'Nave'), ('defense', 'Defensa')], max_length=20)),
                ('stats', models.JSONField(default=dict, help_text='Estadísticas (Ataque, Defensa, Carga, etc.)')),
                ('cost', models.JSONField(default=dict, help_text='Costo base')),
            ],
        ),
        migrations.CreateModel(
            name='Dictator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='dictator_profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Planet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orbit_index', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(9)])),
                ('name', models.CharField(max_length=100)),
                ('owner', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='planets', to='core.dictator')),
            ],
            options={
                'ordering': ['system', 'orbit_index'],
            },
        ),
        migrations.AddField(
            model_name='dictator',
            name='main_planet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='capital_of', to='core.planet'),
        ),
        migrations.CreateModel(
            name='PlanetBuilding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('level', models.IntegerField(default=0)),
                ('building_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.buildingtype')),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planet')),
            ],
            options={
                'unique_together': {('planet', 'building_type')},
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='buildings',
            field=models.ManyToManyField(through='core.PlanetBuilding', to='core.buildingtype'),
        ),
        migrations.CreateModel(
            name='PlanetResource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.BigIntegerField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planet')),
                ('resource_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.resourcetype')),
            ],
            options={
                'unique_together': {('planet', 'resource_type')},
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='resources',
            field=models.ManyToManyField(through='core.PlanetResource', to='core.resourcetype'),
        ),
        migrations.CreateModel(
            name='SolarSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('x', models.IntegerField(help_text='Coordenada X en la galaxia')),
                ('y', models.IntegerField(help_text='Coordenada Y en la galaxia')),
                ('galaxy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='systems', to='core.galaxy')),
            ],
            options={
                'unique_together': {('galaxy', 'x', 'y')},
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='system',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='planets', to='core.solarsystem'),
        ),
        migrations.CreateModel(
            name='PlanetUnit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.BigIntegerField(default=0)),
                ('planet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.planet')),
                ('unit_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.unittype')),
            ],
            options={
                'unique_together': {('planet', 'unit_type')},
            },
        ),
        migrations.AddField(
            model_name='planet',
            name='units',
            field=models.ManyToManyField(through='core.PlanetUnit', to='core.unittype'),
        ),
        migrations.AlterUniqueTogether(
            name='planet',
            unique_together={('system', 'orbit_index')},
        ),
    ]
