# Generated by Django 6.0.2 on 2026-02-26 22:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_planta_eolica_cost'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='last_production_tick',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, help_text='Último momento en que se aplicó la producción de extractores.', null=True),
        ),
    ]
