# Generated by Django 6.0.2 on 2026-02-26 22:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_add_planet_last_production_tick'),
    ]

    operations = [
        migrations.AddField(
            model_name='planet',
            name='production_remainder',
            field=models.JSONField(blank=True, default=dict, help_text='Resto fraccionario de producción por nombre de recurso (para no perder decimales).'),
        ),
    ]
