# Generated by Django 6.0.2 on 2026-02-27 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_add_planet_production_remainder'),
    ]

    operations = [
        migrations.CreateModel(
            name='GameSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_growth_factor', models.FloatField(default=1.5, help_text='Factor de crecimiento del coste por nivel (ej. 1.5)')),
                ('production_speed_multiplier', models.FloatField(default=1.0, help_text='Multiplicador de velocidad de ticks (ej. 60 para 1 min = 1 hora)')),
            ],
            options={
                'verbose_name': 'Configuración Global',
                'verbose_name_plural': 'Configuración Global',
            },
        ),
    ]
